### ISSUE TITLE
Build fails locally under node 17 pnpm 6

### ISSUE THREAD

**Issue by vhscom** [steeze-ui/icons#5]
Pulled down repo and followed instructions in README:

```sh
pnpm install && pnpm package
```

I see two warnings on the install which I ignored. The `package` command, however fails with:

```term
Scope: 10 of 11 workspace projects
packages/builders/octicons-builder package$ pnpm build:icons && svelte-kit package
│ > @steeze-ui/octicons@1.0.0 build:icons /home/vhs/Developer/icons/packages/builders/octicons-builder
│ > node --loader ts-node/esm build.ts
│ (node:75521) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
│ (Use `node --trace-warnings ...` to show where the warning was created)
│ /home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/dist-raw/node-esm-resolve-implementatio
│     throw new ERR_MODULE_NOT_FOUND(
│           ^
│ CustomError: Cannot find module '/home/vhs/Developer/icons/packages/builders/octicons-builder/node_modules/@steeze-ui/icons/dist/index.js' imported from
│     at finalizeResolution (/home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/dist-raw/nod
│     at moduleResolve (/home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/dist-raw/node-esm
│     at Object.defaultResolve (/home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/dist-raw/
│     at /home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/src/esm.ts:152:38
│     at Generator.next (<anonymous>)
│     at /home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/dist/esm.js:8:71
│     at new Promise (<anonymous>)
│     at __awaiter (/home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/dist/esm.js:4:12)
│     at resolve (/home/vhs/Developer/icons/node_modules/.pnpm/ts-node@10.4.0_cb9fa2b677905e47db2aeff929cdeb55/node_modules/ts-node/dist/esm.js:48:16)
│     at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 1.5s
/home/vhs/Developer/icons/packages/builders/octicons-builder:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @steeze-ui/octicons@1.0.0 package: `pnpm build:icons && svelte-kit package`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
```

Node 17.3
pnpm 6.28.0
npm 8.3.2
GNU/Linux 5.15.11

**Comment by JustinVoitel** [comment]
@vhscom Iam not sure what's causing the problem, but I've been switching ts-node with [esmo](https://github.com/antfu/esno) which hopefully resolves your problem!

**Comment by vhscom** [comment]
Thanks, Justin. Also not sure what the issue is. I'll close this but wanted to mention it as it could affect the projects ability to receive contributions.

**Comment by she11sh0cked** [comment]
@JustinVoitel @vhscom The problem is that `pnpm` symlinks `@steeze-ui/icons` to the `packages/core` directory, which is obviously all fine and good, unless the `core` directory hasn't been build yet!

Simply running the following solves this issue:
```bash
cd packages/core
pnpm build
```

This should probably either be mentioned in the README under the **Development** section or be put into the `package` script.

![context](https://user-images.githubusercontent.com/22623152/159115397-bfd6839c-9813-4f78-bcf7-44933350e1eb.png)
